version: "3.8"

services:
  db:
    image: postgres:12.3-alpine
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=${PGSQL_DBNAME:?PGSQL_DBNAME not defined}
      - POSTGRES_USER=${PGSQL_USER:?PGSQL_USER not defined}
      - POSTGRES_PASSWORD=${PGSQL_PASSWD:?PGSQL_PASSWD not defined}
      - POSTGRES_PORT=5432
    restart: unless-stopped

  server:
    build: 
      context: ./
      dockerfile: ./Docker/faraday-server/Dockerfile
    image: cwavesoftware/faraday-server:3.19
    hostname: faraday.server
    ports:
      - "5985:5985"
    volumes:
      - "server_data:/root/.faraday"
    environment: 
      - LISTEN_ADDR=0.0.0.0 
      - PGSQL_HOST=db
      - PGSQL_USER=${PGSQL_USER:?PGSQL_USER not defined}
      - PGSQL_PASSWD=${PGSQL_PASSWD:?PGSQL_PASSWD not defined}
      - PGSQL_DBNAME=${PGSQL_DBNAME:?PGSQL_DBNAME not defined}
      - FARADAY_SUPERUSER_NAME=${FARADAY_SUPERUSER_NAME:?FARADAY_SUPERUSER_NAME not defined}
      - FARADAY_SUPERUSER_EMAIL=${FARADAY_SUPERUSER_EMAIL:?FARADAY_SUPERUSER_EMAIL not defined}
      - FARADAY_SUPERUSER_PASSWORD=${FARADAY_SUPERUSER_PASSWORD:?FARADAY_SUPERUSER_PASSWORD not defined}
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  server_data:

networks: 
  default: 
    name: faradaynet 
